app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('notes.urls', namespace='notes')),
    path('', include('fighting.urls', namespace='fighting')),
    path('', include('history.urls', namespace='history'))
]

fighting/urls.py
from django.urls import path

from fighting import views

app_name = 'fighting'

urlpatterns = [
    path('fighting/', views.fighting, name='fighting'),
    path('fighting/current_fight/', views.current_fight)
]

history/urls.py
from django.urls import path

from history import views

app_name = 'history'

urlpatterns = [
    path('history/', views.history, name='history'),
    path('history/review/', views.review, name='review')
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('characters/', views.characters, name='characters'),
    path('characters/create', views.create, name='create'),
    path('characters/<slug:slug>/', views.display_character, name='display_character'),
    path('characters/<slug:slug>/rename/', views.rename_character, name='rename_character'),
]

notes/urls.py
from django.urls import path

from notes import views

app_name = 'notes'

urlpatterns = [
    path('notes/', views.notes, name='notes'),
]

fighting/models.py
from django.db import models

class Enemie(models.Model):
    name = models.CharField(max_length=50, unique=True)
    max_health = models.IntegerField()
    cur_health = models.IntegerField()
    initiative = models.IntegerField(default=1)
    id_of_fight = models.ForeignKey('Fight', on_delete=models.CASCADE, null=True)
    is_dead = models.BooleanField(default=False)

class Journal(models.Model):
    attacker = models.CharField(max_length=50)
    spell = models.CharField(max_length=100, default='123')
    health = models.IntegerField(null=True, default=5)
    defender = models.CharField(max_length=50)
    id_of_fight = models.ForeignKey('Fight', on_delete=models.CASCADE, null=True)
    is_damage = models.BooleanField(default=True)
    note = models.CharField(max_length=250, default=None, null=True, blank=True)

class Fight(models.Model):
    name = models.TextField(max_length=100, unique=True)
    all_damage = models.IntegerField(default=0)
    all_health = models.IntegerField(default=0)
    count_of_moves = models.IntegerField(default=0)
    is_ended = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

history/models.py
from django.db import models

main/models.py
from django.db import models

class character(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
    level = models.IntegerField(default=10)
    klass = models.CharField(max_length=50)
    rasa = models.CharField(max_length=50)
    max_health = models.IntegerField(default=10)
    cur_health = models.IntegerField(default=10)
    description = models.TextField(blank=True, null=True)
    initiative = models.IntegerField(default=0)
    image = models.ImageField(upload_to='character_images', blank=True, null=True, default='character_images/f0c76a8e2cefa7c75ff4328ec491659b_LNOTyCL.jpg')

    class Meta:
        db_table = 'character'
        verbose_name = 'Персонажа'
        verbose_name_plural = 'Персонажи'

notes/models.py
from django.db import models

class Notes(models.Model):
    textData = models.TextField(max_length=500)
    date = models.DateField(auto_now_add=True)

fighting/forms.py
from .models import Journal
from django import forms

main/forms.py
from .models import character
from django.forms import ModelForm, TextInput

class characterForm(ModelForm):
    class Meta:
        model = character
        fields = ['name','klass','rasa']
        widgets = {
            'name' : TextInput(attrs={
                'placeholder' : 'Введите Имя'
            }),
            'klass' : TextInput(attrs={
                'placeholder' : 'Введите Класс'
            }),
            'rasa' : TextInput(attrs={
                'placeholder' : 'Введите Расу'
            })}
        
class renameForm(ModelForm):
    class Meta:
        model = character
        fields = ['name', 'level','max_health','cur_health', 'klass', 'rasa', 'description']
        widgets = {
            'name' : TextInput(attrs={
                'id' : 'name',
            }),
            'level' : TextInput(attrs={
                'id' : 'level',
            }),
            'max_health' : TextInput(attrs={
                'id' : 'max_health',
            }),
            'cur_health' : TextInput(attrs={
                'id' : 'cur_health',
            }),
            'klass' : TextInput(attrs={
                'id' : 'klass',
            }),
            'rasa' : TextInput(attrs={
                'id' : 'rasa',
            }),
            'description' : TextInput(attrs={
                'id' : 'description',
            })
        }

notes/forms.py
from .models import Notes
from django.forms import ModelForm, TextInput

class NotesForm(ModelForm):
    class Meta:
        model = Notes
        fields =['textData']

        widgets = {
            'textData' : TextInput(attrs={
                'class' : 'form-place',
                'placeholder' : 'Введите заметку',
            })
        }

fighting/views.py
from django.shortcuts import render, redirect

from main import models
from fighting.models import Journal, Fight, Enemie

def fighting(request):
    if request.method == 'POST':
        if 'deleting-fight-id' in request.POST:
            fight_id = request.POST.get('deleting-fight-id')
            Fight.objects.get(id=fight_id).delete()
        else:
            name = request.POST.get('name-of-fight')
            Fight.objects.create(name=name)

    fights_data = Fight.objects.all().order_by('-id')

    context = {'title' : 'Режим Боя',
               'fights' : fights_data}

    return render(request,'main/fighting.html', context)

def current_fight(request):
    fight_id = request.GET.get('fight_id')
    current_fight = Fight.objects.get(id = fight_id)

    if request.method == 'POST':
        if 'attacker' in request.POST:
            # Запрос на добавление записи в журнал
            attacker = request.POST.get('attacker')
            spell = request.POST.get('spell')
            defender = request.POST.get('defender')
            health = request.POST.get('health')
            Journal.objects.create(attacker=attacker, spell=spell, defender=defender,health=health, id_of_fight = current_fight)
            current_fight.all_damage += int(health)
            current_fight.save()
            current_enemie = Enemie.objects.get(name=defender)
            current_enemie.cur_health -= int(health)
            if current_enemie.cur_health <= 0:
                # Добавить Доп.Запись если кто то умер
                current_enemie.is_dead = True
                current_enemie.cur_health = 0
                Journal.objects.create(attacker=attacker, spell=spell, defender=defender,health=health, id_of_fight = current_fight, is_damage = False)
            current_enemie.save()
        elif 'end_of_fight_id' in request.POST:
            # Закончить текущий бой
            id_of_fight = request.POST.get('end_of_fight_id')
            fight = Fight.objects.get(id=id_of_fight)
            fight.is_ended = True
            fight.save()
            print(id_of_fight)
            return redirect('fighting:fighting')
        elif 'continue_of_fight_id' in request.POST:
            # Возобновить бой
            id_of_fight = request.POST.get('continue_of_fight_id')
            fight = Fight.objects.get(id=id_of_fight)
            fight.is_ended = False
            fight.save()
            print(id_of_fight)
            return redirect('fighting:fighting')
        else:
            # Запрос на добавление врага
            name_enemie = request.POST.get('name_enemie')
            health_enemie = request.POST.get('health_enemie')
            initiative_enemy = request.POST.get('initiative_enemie')
            Enemie.objects.create(name = name_enemie, max_health = health_enemie, cur_health = health_enemie, id_of_fight = current_fight, initiative = initiative_enemy)
    
    characters_data = models.character.objects.all().order_by('-initiative')

    enemies_data = Enemie.objects.all().filter(id_of_fight = current_fight).order_by('-initiative')
    journal_data = Journal.objects.all().filter(id_of_fight = current_fight).order_by('-id')


    context = {'title' : 'Бой',
               'characters' : characters_data,
               'enemies' : enemies_data,
               'fight' : current_fight,
               'journals' : journal_data,}
    return render(request, 'main/current_fight.html', context)

history/views.py
from django.shortcuts import render

from fighting.models import Fight, Journal

def history(request):
    fight_data = Fight.objects.all()

    context = {'title' : 'История',
               'fights' : fight_data,
    }

    return render(request, 'main/history.html', context)

def review(request):
    fight_id = request.GET.get('fight_id')
    current_fight = Fight.objects.get(id=fight_id)

    journal_data = Journal.objects.all().filter(id_of_fight = current_fight).order_by('-id')

    context = {
        'title' : 'Обзор',
        'journals' : journal_data
    }
    return render(request,'main/review.html', context)

main/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from main.models import character
from main.forms import characterForm, renameForm

def characters(request):
    charactersdata = character.objects.all()
    
    context = {
        'title' : 'Персонажи',
        'characters' : charactersdata,
    }
    return render(request, 'main/characters.html', context)

def display_character(request, slug):
    if request.method == 'POST':
        character_id = request.POST.get('character_id')
        character.objects.get(id=character_id).delete()
        return redirect('main:characters')
    
    character_d = character.objects.get(slug=slug)
    
    charactersdata = character.objects.all()

    context = {
        'title' : 'Персонажи',
        'characters' : charactersdata,
        'character_d' : character_d
    }
    
    return render(request, 'main/display.html', context)

def rename_character(request, slug):
    character_d = character.objects.get(slug=slug)

    charactersdata = character.objects.all()

    if request.method == 'POST':
        name = request.POST.get('name')
        level = request.POST.get('level',15)
        max_health = request.POST.get('max_health',10)
        cur_health = request.POST.get('cur_health',10)
        klass = request.POST.get('klass')
        rasa = request.POST.get('rasa')
        description = request.POST.get('description')
        character_d.name = name
        character_d.level = level
        character_d.max_health = max_health
        character_d.cur_health = cur_health
        character_d.klass = klass
        character_d.rasa = rasa
        character_d.description = description
        character_d.save()
        return redirect('main:characters')

    form = renameForm()

    context = {
        'title' : 'Редактирование',
        'character_d' : character_d,
        'characters' : charactersdata,
        'form' : form
    }

    return render(request, 'main/rename.html', context)

def create(request):
    if request.method == 'POST':
        form = characterForm(request.POST)
        if form.is_valid():
            form.save()

    charactersdata = character.objects.all()
    
    form = characterForm()
    
    context = {
        'title' : 'Создать Персонажа',
        'characters' : charactersdata,
        'form' : form,
    }
    return render(request, 'main/create.html', context)

def home(request):
    return render(request,'main/home.html')

notes/views.py
import json
from django.shortcuts import render

from notes.models import Notes
from notes.forms import NotesForm

def notes(request):
    if request.method == 'POST':
        if 'noteId' not in request.POST:
            form = NotesForm(request.POST)
            if form.is_valid():
                form.save()
        else:
            id_data = request.POST.get('noteId')
            Notes.objects.get(id=int(id_data)).delete()

    form = NotesForm()

    data = Notes.objects.all().order_by('-id')
    context = {'data' : data,
               'title' : 'Заметки',
               'form' : form}
    return render(request, "main/notes.html", context)

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link 
            rel="stylesheet" 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
            crossorigin="anonymous"
        />
    <link rel="stylesheet" href="{% static "deps/css/base.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
    <nav class="navigation-bar">
        <div class="navigation-bar-items">
            <a class="navigation-bar-item" id="characters" href="{% url "main:home" %}">Главная</a>
            <a class="navigation-bar-item" id="characters" href="{% url "main:characters" %}">Персонажи</a>
            <a class="navigation-bar-item" id="characters" href="{% url "fighting:fighting"%}">Режим Боя</a>
            <a class="navigation-bar-item" id="characters" href="{% url "notes:notes" %}">Заметки</a>
            <a class="navigation-bar-item" id="characters" href="{% url "history:history" %}">История</a>
            <a class="navigation-bar-item" id="characters" href="{% url "admin:index" %}">Админ-Панель</a>
        </div>
    </nav>
    {% block content %}{% endblock %}

main/templates/main/characters.html
{% extends "main/base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static "deps/css/characters.css" %}">
{% endblock %}

{% block content %}
<div class="maindiv">
    <div class="left">

        {% for character in characters %}

            <a class="character" href="{% url "main:display_character" character.slug %}">{{ character.name }}</a>

        {% endfor %}

        <a class='character' href="{% url "main:create" %}"> Добавить Персонажа </a>
    </div>
    {% block right %}{% endblock %}
    </div>
{% endblock  %}

main/templates/main/create.html
{% extends "main/characters.html" %}

{% load static %}

{% block right %}
<div class="right">
    <div class="image_name">
        <img src="{% static "deps/image/melisa.jpg" %}" height="150px" width="150px">
        <p1>Мелисаа</p1>
    </div>
    <form method='post'>
        {% csrf_token %}
        {{ form.name }}<br>
        {{ form.klass }}<br>
        {{ form.rasa }}<br>
        <button class='button btn-success' type='submit'> Добавить Персонажа </button>
    </form>
    <div class="optional_information"></div>
{% endblock %}

main/templates/main/current_fight.html
{% extends "main/base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static "deps/css/curren_fight.css" %}">
{% endblock %}

{% block content%}
<div class="name-of-fight">{{ fight.name }} {% if fight.is_ended %} (Закончен) {% endif %}</div>
<div class="main-wrapper">
<div class="list-group-items">
    <div class="characters-list">
        Союзники
        {% for character in characters %}
        <div class="character-item">
            {{ character.name }} | {{ character.cur_health }} хп | {{ character.initiative }}
        </div>
        {% endfor %}
    </div>
    <div class="enemies-list">
        Враги
        {% for enemie in enemies %}
        <div class="enemies-item">
            {{ enemie.name }} | {{ enemie.cur_health }} хп | {{ enemie.initiative }}
            {% if enemie.is_dead %} (Мертв) {% endif %}
        </div>
        {% endfor %}
        {% if fight.is_ended == False %}
        <form method='POST'>
            {% csrf_token %}
            <input name='name_enemie' placeholder='Имя Врага'></input>
            <input name='health_enemie' placeholder='ХП Врага'></input>
            <input name='initiative_enemie' placeholder='Инициатива Врага'></input>
            <button type='submitt'>Добавить</button>
        </form>
        {% endif %}
    </div>
</div>
{% if fight.is_ended == False %}
<div class="input-journal">
<form method='POST'>
    {% csrf_token %}
    <select name='attacker'>
        {% for character in characters %}
        <option>{{character.name}}</option>
        {% endfor %}
        {% for enemie in enemies %}
        <option>{{enemie.name}}</option>
        {% endfor %}
    </select>
    использует
    <input name='spell' placeholder='Введите заклинание'></input>
    <select name='defender'>
        {% for enemie in enemies %}
        <option>{{enemie.name}}</option>
        {% endfor %}
        {% for character in characters %}
        <option>{{character.name}}</option>
        {% endfor %}
    </select>
    и наносит 
    <input name='health' placeholder='Введите урон'></input>
    единиц урона
    <button type='submitt'>Отправить</button>
</form>
</div>
{% endif %}
    <div class="journal-list">
        <p1> Журнал Боя </p1>
        {% for journal in journals %}
        <ul>
            {% if journal.is_damage %}
            {{ journal.attacker }} использует {{ journal.spell }} и наносит {{ journal.defender }} {{ journal.health }} единиц урона
            {% else %}
            {{ journal.defender }} был убит {{ journal.attacker }}
            {% endif %}
        </ul>
        {% endfor %}
    </div>
    {% if fight.is_ended == False %}
    <div class="end-of-fight-button">
        <form method='POST'>
            {% csrf_token %}
            <button name='end_of_fight_id' value='{{ fight.id }}'>Закончить Бой</button>
        </form>
    </div>
    {% else %}
    <div class="continue-of-fight-button">
        <form method='POST'>
            {% csrf_token %}
            <button name='continue_of_fight_id' value='{{ fight.id }}'>Возобновить Бой</button>
        </form>
    </div>
    {% endif %}
</div>
{% endblock %}

main/templates/main/display.html
{% extends "main/characters.html" %}

{% load static %}

{% block right %}
<div class="right">
    <div class="image_name">
        <img src="{{ character_d.image.url }}" height="150px" width="150px">
        <p1>{{ character_d.name }}</p1>
    </div>
    <div class="main_infromation">
        <div class="main_information_item">
            <p1>Класс : {{ character_d.klass }}</p1>
        </div>
        <div class="main_information_item">
            <p1>Раса : {{ character_d.rasa }}</p1>
        </div>
        <div class="main_information_item">
            <p1>Уровень : {{ character_d.level}}</p1>
        </div>
        <div class="main_information_item">
            <p1>Опыт : 1700</p1>
        </div>
        <div class="main_information_item">
            <p1>Максимально ХП : {{ character_d.max_health }}</p1>
        </div>
        <div class="main_information_item">
            <p1>Текущее ХП : {{ character_d.cur_health }}</p1>
        </div>
        <div class="main_information_item">
            <p1> Описание : {{ character_d.description }}<p1>
            </div>
    </div>  
    <div class="wrapper-buttons">
        <div class="button-button">
            <form method='get' action='rename/'>
                <button class='delete-button' type='submit' name='character_id_rename' value='{{ character_d.id }}'>Редактировать</button>
            </form>
        </div>
        <div class="button-button">
            <form method='post'>
                {% csrf_token %}
                <button class='delete-button' type='submit' name='character_id' value='{{ character_d.id }}'>Удалить</button>
            </form>
        </div>
    </div>
{% endblock %}

main/templates/main/fighting.html
{% extends "main/base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static "deps/css/fighting.css" %}">
{% endblock %}

{% block content %}
<table class='table'>
    <thead>
        <tr>
            <th>Название Боя</th>
            <th>Статус</th>
            <th>Дата</th>
            <th>Подробнее</th>
            <th>Удалить Бой</th>
        </tr>
    </thead>
    <tbody>
        {% for fight in fights %}
        <tr>
            <td>{{fight.name}}</td>
            <td>
                {% if fight.is_ended %}
                Закончен
                {% else %}
                Продолжается
                {% endif %}
            </td>
            <td>{{fight.date}}</td>
            <td>
                <div>
                    <form method='get' action='current_fight/'>
                        <button class='button' type='submit' name='fight_id' value='{{ fight.id }}'>Перейти</button>
                    </form>
                </div>
            </td>
            <td>
                <div class="delete-button-wrapper">
                    <form method='POST'>
                        {% csrf_token %}
                        <button class='button' name='deleting-fight-id' value = {{ fight.id }}>Удалить</button>
                    </form>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tdoby>
</table>
<div class="wrapper">
<form method='POST'>
    {% csrf_token %}
    <input placeholder='Введите Название Боя' name='name-of-fight'></input>
    <button class = 'add-button' type='submit'>Добавить Бой</button>
</form>
</div>
{% endblock  %}

main/templates/main/history.html
{% extends "main/base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static "deps/css/history.css" %}">
{% endblock %}

{% block content%}
<table class='table'>
    <thead>
        <tr>
            <th>Название Боя</th>
            <th>Урон</th>
            <th>Вылечено</th>
            <th>Количество Ходов</th>
            <th>Дата</th>
            <th>Подробнее</th>
        </tr>
    </thead>
    <tbody>
        {% for fight in fights%}
        <tr>
            <td>{{ fight.name }}</td>
            <td>{{ fight.all_damage }}</td>
            <td>{{ fight.all_health  }}</td>
            <td>{{ fight.count_of_moves }}</td>
            <td>{{ fight.date }}</td>
            <td>
                <div>
                    <form method='get' action='review/'>
                        <button class='delete-button' type='submit' name='fight_id' value='{{ fight.id }}'>Перейти</button>
                    </form>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

main/templates/main/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DND</title>
    <link rel="stylesheet" href="{% static "deps/css/home.css" %}">
</head>
<body>
    <div class="wrapper">
        <div class="main-text">Dungeons And Dragons</div>
        <a href="{% url "main:characters" %}" class="btn-flip" data-back="Игру" data-front="Начать"></a>
    </div>
</body>
</html>

main/templates/main/notes.html
{% extends "main/base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static "deps/css/notes.css" %}">
{% endblock %}

{% block content %}
<div class="maindiv">
    <p1 class='maindiv-head-notes'> Заметки </p1>
    <ul class="notes-group-items">
        {% for note in data %}
        <li class="notes-item">
            <div class="same-note">{{ note.date }} : {{ note.textData }}</div>
            <form method='post'>
                {% csrf_token %}
                <button class='delete-btn' name='noteId' value='{{ note.id }}'>
                    <img class='delete-btn-img' src='{% static "deps/css/krestik.png" %}'></img>
                </button>
            </form>
        </li>    
        {% endfor %}
    </ul>
    <form method='post'>
        {% csrf_token %}
        {{ form.textData }}<br>
        <button class='button' type='submit'> Добавить Заметку </button>
    </form>
</div>
{% endblock %}

main/templates/main/rename.html
{% extends "main/characters.html" %}

{% load static %}

{% block right %}
<div class="right">
    <div class="image_name">
        <img src="{{ character_d.image.url }}" height="150px" width="150px">
        <p1>{{ character_d.name }}</p1>
    </div>
    <div class="main_infromation">
        <form method='post'>
            {% csrf_token %}
            <p1>Имя : </p1>
            {{ form.name }}<br>
            <p1>Уровень : </p1>
            {{ form.level }}<br>
            <p1>Максимально ХП : </p1>
            {{ form.max_health }}<br>
            <p1>Текущее ХП : </p1>
            {{ form.cur_health }}<br>
            <p1>Класс : </p1>
            {{ form.klass }}<br>
            <p1>Раса : </p1>
            {{ form.rasa }}<br>
            <p1>Описание : </p1>
            {{ form.description }}<br>
            <script>
                document.getElementById('name').value = '{{ character_d.name }}';
                document.getElementById('level').value = '{{ character_d.level }}';
                document.getElementById('max_health').value = '{{ character_d.max_health }}';
                document.getElementById('cur_health').value = '{{ character_d.cur_health }}';
                document.getElementById('klass').value = '{{ character_d.klass }}';
                document.getElementById('rasa').value = '{{ character_d.rasa }}';
                document.getElementById('description').value = '{{ character_d.description }}';
            </script>
            <button class='button btn-success' type='submit'> Редактировать </button>
        </form>
        
    </div>  
    
{% endblock %}

main/templates/main/review.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}

<p1> Журнал Боя </p1>
    <ul>
        {% for journal in journals %}
        <li class="journal-item">
            {% if journal.is_damage %}
            {{ journal.attacker }} использует {{ journal.spell }} и наносит {{ journal.defender }} {{ journal.health }} единиц урона
            {% else %}
            {{ journal.defender }} был убит {{ journal.attacker }}
            {% endif %}
        </li>
        {% endfor %}
    </ul>
{% endblock %}